import {UserProfileBasicInfo, UserProfileBasicInfoFormValues} from '../../../types/graphql/userProfiles';

export const initialValues: UserProfileBasicInfoFormValues = {
  id: 0,
  first_name: '',
  last_name: '',
  date_of_birth: '',
  birth_last_name: '',
  country_of_birth: '',
  city_of_birth: '',
  nationality: '',
  citizenship: '',
  address: '',
  father_name: '',
  mother_name: '',
  mother_birth_last_name: '',
  bank_account: '',
  bank_name: '',
  official_personal_id: '',
  official_personal_document_number: '',
  official_personal_document_issuer: '',
  gender: '',
  single_parent: false,
  housing_done: false,
  revisor_role: false,
  housing_description: '',
  marital_status: '',
  date_of_taking_oath: '',
  date_of_becoming_judge: '',
  email: '',
  phone: '',
  national_minority: '',
  secondary_email: '',
  pin: '',
  password: '',
  middle_name: '',
  position_in_organization_unit_id: 0,
  role_id: 0,
  contracts: [],
};
